const starData = [
    {
      nameKo: "처녀자리",
      nameLt: "Virgo",
      nameEn: "the Virgin, the Maiden",
      whereSee: "적경 13h 20m, 적위 -2°",
      whenMeridian: "6월 5일 오후 9시",
      numOfStar: "99개",
      size: "1294.428sr(2위)",
      tags: ["봄철 밤하늘 별자리","황도 제6궁"],
      emoji: "♍",
    },
    {
      nameKo: "거문고자리",
      nameLt: "Lyra",
      nameEn: "the Lyre, the Harp",
      whereSee: "적경 18h 45m, 적위 +36°",
      whenMeridian: "8월 27일 오후 9시",
      numOfStar: "35개",
      size: "286.476sr(52위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "독수리자리",
      nameLt: "Aquila",
      nameEn: "the Eagle",
      whereSee: "적경 19h 30m, 적위 +2°",
      whenMeridian: "9월 8일 오후 9시",
      numOfStar: "70개",
      size: "652.473sr(22위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "뱀자리 / 뱀주인자리",
      nameLt: "Serpens / Ophiuchus",
      nameEn: "the Snake, the Serpent / the Serpent Bearer, the Serpentholder",
      whereSee: "적경 (머리)15h 35m, 적위 +8°, (꼬리)적경 18h 00m, 적위 -5° / 적경 17h 10m, 적위 -4°",
      whenMeridian: "(머리)7월 10일 오후 9시, (꼬리)8월 15일 오후 9시 / 8월 3일 오후 9시",
      numOfStar: "54개 / 84개",
      size: "636.928sr(23위) / 948.340sr(11위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "페가수스자리",
      nameLt: "Pegasus",
      nameEn: "the Horse, the Winged Horse, the Flying Horse",
      whereSee: "적경 22h 30m, 적위 +17°",
      whenMeridian: "10월 23일 오후 9시",
      numOfStar: "98개",
      size: "1120.794sr(7위)",
      tags: ["가을철 밤하늘 별자리"],
    },
    {
      nameKo: "물병자리 / 남쪽물고기자리",
      nameLt: "Aquarius / Piscis Austrinus",
      nameEn: "the Water-Bearer, the Water-Man, the Cupbearer / the Southern Fish",
      whereSee: "적경 22h 20m, 적위 -13° / 적경 22h 00m, 적위 -32°",
      whenMeridian: "10월 20일 오후 9시 / 10월 15일 오후 9시",
      numOfStar: "96개 / 26개",
      size: "979.854sr(10위) / 245.375sr(60위)",
      tags: ["가을철 밤하늘 별자리","황도 제11궁"],
      emoji: "♒",
    },
    {
      nameKo: "도마뱀자리 / 조랑말자리",
      nameLt: "Lacerta / Equuleus",
      nameEn: "the Lizard / the Foal, the Colt, the Little Horse",
      whereSee: "적경 22h 25m, 적위 +43° / 적경 21h 10m, 적위 +6°삼각형자리 / 양자리",
      whenMeridian: "10월 22일 오후 9시 / 10월 3일 오후 9시",
      numOfStar: "36개 / 10개",
      size: "200.688sr(68위) / 71.641sr(87위)",
      tags: ["가을철 밤하늘 별자리"],
    },
    {
      nameKo: "쌍둥이자리",
      nameLt: "Gemini",
      nameEn: "the Twins",
      whereSee: "적경 7h 00m, 적위 +22°",
      whenMeridian: "3월 1일 오후 9시",
      numOfStar: "75개",
      size: "513.761sr(30위)",
      tags: ["겨울철 밤하늘 별자리","황도 제3궁"],
      emoji: "♊",
    },
    {
      nameKo: "오리온자리",
      nameLt: "Orion",
      nameEn: "the Great Hunter, the Warrior",
      whereSee: "적경 5h 20m, 적위 +3°",
      whenMeridian: "2월 3일 오후 9시",
      numOfStar: "125개",
      size: "594.120sr(26위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "케페우스자리",
      nameLt: "Cepheus",
      nameEn: "Cepheus, the king",
      whereSee: "적경 22h 00m, 적위 +70°",
      whenMeridian: "10월 15일 밤 9시",
      numOfStar: "96개",
      size: "587.787sr(27위)",
      tags: ["북쪽 밤하늘 별자리"],
    },
    {
      nameKo: "까마귀자리 / 컵자리",
      nameLt: "Corvus / Crater",
      nameEn: "the Crow / the Cup, the Bowl, the Goblet",
      whereSee: "적경 12h 20m, 적위 -18° / 적경 11h 20m, 적위 -15°",
      whenMeridian: "5월 21일 오후 9시 / 5월 6일 오후 9시",
      numOfStar: "18개 / 17개",
      size: "183.801sr(70위) / 282.398sr(53위)",
      tags: ["봄철 밤하늘 별자리"],
    },
    {
      nameKo: "마차부자리",
      nameLt: "Auriga",
      nameEn: "the Charioteer, the Waggoner",
      whereSee: "적경 6h 00m, 적위 +42°",
      whenMeridian: "2월 13일 오후 9시",
      numOfStar: "78개",
      size: "657.438sr(21위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "작은개자리",
      nameLt: "Canis Minor",
      nameEn: "the Little Dog. the Smaller Dog",
      whereSee: "적경 7h 30m, 적위 +6°",
      whenMeridian: "3월 9일 오후 9시",
      numOfStar: "25개",
      size: "183.367sr(71위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "바다뱀자리",
      nameLt: "Hydra",
      nameEn: "the Sea Serpent, the Water Monster",
      whereSee: "적경 10h 30m, 적위 -20°",
      whenMeridian: "4월 23일 오후 9시",
      numOfStar: "126개",
      size: "1302.844sr(1위)",
      tags: ["봄철 밤하늘 별자리"],
    },
    {
      nameKo: "돌고래자리",
      nameLt: "Delphinus",
      nameEn: "the Dolphin",
      whereSee: "적경 20h 35m, 적위 +12°",
      whenMeridian: "9월 24일 오후 9시",
      numOfStar: "19개",
      size: "188.549sr(69위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "안드로메다자리",
      nameLt: "Andromeda",
      nameEn: "the Chained Lady, the Chained Woman",
      whereSee: "적경 0h 40m, 적위 +38°",
      whenMeridian: "11월 25일 오후 9시",
      numOfStar: "84개",
      size: "722.278sr(19위)",
      tags: ["가을철 밤하늘 별자리"],
    },
    {
      nameKo: "황소자리",
      nameLt: "Taurus",
      nameEn: "the Bull",
      whereSee: "적경 4h 30m, 적위 +18°",
      whenMeridian: "1월 22일 오후 9시",
      numOfStar: "143개",
      size: "797.249sr(17위)",
      tags: ["겨울철 밤하늘 별자리","황도 제2궁"],
      emoji: "♉",
    },
    {
      nameKo: "큰곰자리 / 작은곰자리",
      nameLt: "Ursa Major / Ursa Minor",
      nameEn: "the Great Bear / the Little Bear",
      whereSee: "적경 11h 00m, 적위 +58° / 적경 15h 40m, 적위 +78°",
      whenMeridian: "5월 1일 밤 9시 / 7월 11일 밤 9시",
      numOfStar: "126개 / 26개",
      size: "1279.660sr(3위) / 255.864sr(56위)",
      tags: ["북쪽 밤하늘 별자리"],
    },
    {
      nameKo: "기린자리 / 용자리",
      nameLt: "Camelopardalis / Draco",
      nameEn: "the Giraffe / the Dragon",
      whereSee: "적경 5h 40m, 적위 +70° / 적경 17h 00m, 적위 +60°",
      whenMeridian: "2월 8일 밤 9시 / 7월 31일 밤 9시",
      numOfStar: "74개 / 123개",
      size: "756.828sr(18위) / 1082.952sr(8위)",
      tags: ["북쪽 밤하늘 별자리"],
    },
    {
      nameKo: "카시오페이아자리",
      nameLt: "Cassiopeia",
      nameEn: "Cassiopeia, the lady in her chair",
      whereSee: "적경 1h 00m, 적위 +60°",
      whenMeridian: "11월 30일 밤 9시",
      numOfStar: "94개",
      size: "598.407sr(25위)",
      tags: ["북쪽 밤하늘 별자리"],
    },
    {
      nameKo: "머리털자리",
      nameLt: "Coma Berenices",
      nameEn: "the Hair of Berenice, Berenice's Hair",
      whereSee: "적경 12h 40m, 적위 +23°",
      whenMeridian: "5월 26일 오후 9시",
      numOfStar: "38개",
      size: "386.475sr(42위)",
      tags: ["봄철 밤하늘 별자리"],
    },
    {
      nameKo: "사냥개자리 / 왕관자리",
      nameLt: "Canes Venatici / Corona Borealis",
      nameEn: "the Hunting Dogs / the Northern Crown",
      whereSee: "적경 13h 00m, 적위 +40° / 적경 15h 40m, 적위 +30°",
      whenMeridian: "5월 31일 오후 9시 / 7월 11일 오후 9시",
      numOfStar: "32개 / 25개",
      size: "465.194sr(38위) / 178.710sr(73위)",
      tags: ["봄철 밤하늘 별자리"],
    },
    {
      nameKo: "천칭자리",
      nameLt: "Libra",
      nameEn: "the Balance, the Scale",
      whereSee: "적경 15h 10m, 적위 -14°",
      whenMeridian: "7월 4일 오후 9시",
      numOfStar: "50개",
      size: "538.052sr(29위)",
      tags: ["봄철 밤하늘 별자리","황도 제7궁"],
      emoji: "♎",
    },
    {
      nameKo: "살쾡이자리 / 작은사자자리 / 육분의자리",
      nameLt: "Lynx / Leo Minor / Sextans",
      nameEn: "the Lynx / the Little Lion, the Lesser Lion / the Sextant",
      whereSee: "적경 7h 50m, 적위 +45° / 적경 10h 20m, 적위 +33° / 적경 10h 10m, 적위 -1°",
      whenMeridian: "3월 14일 오후 9시 / 4월 20일 오후 9시 / 4월 18일 오후 9시",
      numOfStar: "61개 / 22개 / 17개",
      size: "545.386sr(28위) / 231.956sr(64위) / 313.515sr(47위)",
      tags: ["봄철 밤하늘 별자리"],
    },
    {
      nameKo: "궁수자리",
      nameLt: "Sagittarius",
      nameEn: "the Archer",
      whereSee: "적경 19h 00m, 적위 -25°",
      whenMeridian: "8월 31일 오후 9시",
      numOfStar: "113개",
      size: "867.432sr(15위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "백조자리",
      nameLt: "Cygnus",
      nameEn: "the Swan",
      whereSee: "적경 20h 30m, 적위 +43°",
      whenMeridian: "9월 23일 오후 9시",
      numOfStar: "139개",
      size: "803.983sr(16위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "염소자리",
      nameLt: "Capricornus",
      nameEn: "the Goat, the Sea Goat the Goathorn",
      whereSee: "적경 20h 50m, 적위 -20°",
      whenMeridian: "9월 28일 오후 9시",
      numOfStar: "47개",
      size: "413.947sr(40위)",
      tags: ["여름철 밤하늘 별자리","황도 제10궁"],
      emoji: "♑",
    },
    {
      nameKo: "전갈자리",
      nameLt: "Scorpius",
      nameEn: "the Scorpion",
      whereSee: "적경 16h 20m, 적위 -6°",
      whenMeridian: "7월 21일 오후 9시",
      numOfStar: "101개",
      size: "496.783sr(33위)",
      tags: ["여름철 밤하늘 별자리","황도 제8궁"],
      emoji: "♏",
    },
    {
      nameKo: "헤르쿨레스자리",
      nameLt: "Hercules",
      nameEn: "Hercules",
      whereSee: "적경 17h 10m, 적위 +27°",
      whenMeridian: "8월 3일 오후 9시",
      numOfStar: "142개",
      size: "1225.148sr(5위)",
      tags: ["여름철 밤하늘 별자리"],
    },
    {
      nameKo: "방패자리 / 작은여우자리 / 화살자리",
      nameLt: "Scutum / Vulpecula / Sagitta",
      nameEn: "the Shield, Sobieski's Shield / the Little Fox / the Arrow",
      whereSee: "적경 18h 40m, 적위 -10° / 적경 20h 10m, 적위 +25° / 적경 19h 40m, 적위 +18°",
      whenMeridian: "8월 23일 오후 9시 / 9월 18일 오후 9시 / 9월 10일 오후 9시",
      numOfStar: "19개 / 45개 / 15개",
      size: "109.114sr(84위) / 268.165sr(55위) / 79.932sr(86위)",
      tags: ["여름철 밤하늘 별자리","황도 제9궁"],
      emoji: "♐",
    },
    {
      nameKo: "고래자리",
      nameLt: "Cetus",
      nameEn: "the Whale",
      whereSee: "적경 1h 45m, 적위 -12°",
      whenMeridian: "12월 11일 오후 9시",
      numOfStar: "110개",
      size: "1231.411sr(4위)",
      tags: ["가을철 밤하늘 별자리"],
    },
    {
      nameKo: "물고기자리",
      nameLt: "Pisces",
      nameEn: "the Fishes",
      whereSee: "적경 0h 20m, 적위 +10°",
      whenMeridian: "11월 20일 오후 9시",
      numOfStar: "81개",
      size: "889.417sr(14위)",
      tags: ["가을철 밤하늘 별자리","황도 제12궁"],
      emoji: "♓",
    },
    {
      nameKo: "페르세우스자리",
      nameLt: "Perseus",
      nameEn: "Perseus",
      whereSee: "적경 3h 20m, 적위 +42°",
      whenMeridian: "1월 4일 오후 9시",
      numOfStar: "98개",
      size: "614.997sr(24위)",
      tags: ["가을철 밤하늘 별자리"],
    },
    {
      nameKo: "삼각형자리 / 양자리",
      nameLt: "Triangulum / Aries",
      nameEn: "the Triangle / the Ram",
      whereSee: "적경 2h 00m, 적위 +32° / 적경 2h 30m, 적위 +20°",
      whenMeridian: "12월 15일 오후 9시 / 12월 25일 오후 9시",
      numOfStar: "19개 / 56개",
      size: "131.847sr(78위) / 441.395sr(39위)",
      tags: ["가을철 밤하늘 별자리","황도 제1궁"],
      emoji: "♈",
    },
    {
      nameKo: "게자리",
      nameLt: "Cancer",
      nameEn: "the Crab",
      whereSee: "적경 8h 30m, 적위 +20°",
      whenMeridian: "3월 24일 오후 9시",
      numOfStar: "52개",
      size: "505.872sr(31위)",
      tags: ["겨울철 밤하늘 별자리","황도 제4궁"],
      emoji: "♋",
    },
    {
      nameKo: "에리다누스자리",
      nameLt: "Eridanus",
      nameEn: "the River, River Eridanus",
      whereSee: "적경 3h 50m, 적위 -30°",
      whenMeridian: "1월 12일 오후 9시",
      numOfStar: "129개",
      size: "1137.919sr(6위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "외뿔소자리 / 토끼자리",
      nameLt: "Monoceros / Lepus",
      nameEn: "the Unicorn / the Hare",
      whereSee: "7h 00m 적위 -3° / 적경 5h 25m, 적위 -20°",
      whenMeridian: "3월 1일 오후 9시 / 2월 4일 오후 9시",
      numOfStar: "73개 / 46개",
      size: "481.560sr(35위) / 290.291sr(51위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "큰개자리",
      nameLt: "Canis Major",
      nameEn: "the Greater Dog. the Lager Dog",
      whereSee: "적경 6h 40m, 적위 -24°",
      whenMeridian: "2월 24일 오후 9시",
      numOfStar: "87개",
      size: "380.118sr(43위)",
      tags: ["겨울철 밤하늘 별자리"],
    },
    {
      nameKo: "사자자리",
      nameLt: "Leo",
      nameEn: "the Lion",
      whereSee: "적경 10h 30m, 적위 +15°",
      whenMeridian: "4월 23일 오후 9시",
      numOfStar: "80개",
      size: "946.964sr(12위)",
      tags: ["봄철 밤하늘 별자리","황도 제5궁"],
      emoji: "♌",
    },
    {
      nameKo: "목동자리",
      nameLt: "Bootes",
      nameEn: "the Herdsman",
      whereSee: "적경 14h 35m, 적위 +30°",
      whenMeridian: "6월 24일 오후 9시",
      numOfStar: "86개",
      size: "906.831sr(13위)",
      tags: ["봄철 밤하늘 별자리"],
    }
  ];